name: temp_mail
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  get: ^4.6.5
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  shimmer: ^2.0.0
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

